/**
 * App logo: a speech bubble (messaging) with a send arrow inside (outbound SMS).
 *
 * Kept in sync with frontend/public/favicon.svg and the PNG icons generated by
 * scripts/make_icons.py -- if you change the geometry here, re-run that script.
 */
export default function BrandMark({ className = 'w-8 h-8' }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 64 64"
      className={className}
      role="img"
      aria-label="SMS SENDER"
      xmlns="http://www.w3.org/2000/svg"
    >
      <defs>
        <linearGradient id="brandmark-bg" x1="0" y1="0" x2="1" y2="1">
          <stop offset="0" stopColor="#2563eb" />
          <stop offset="1" stopColor="#4f46e5" />
        </linearGradient>
      </defs>
      <rect width="64" height="64" rx="14" fill="url(#brandmark-bg)" />
      <path
        d="M20.2 14.4h23.6a6.7 6.7 0 0 1 6.7 6.7v13.8a6.7 6.7 0 0 1-6.7 6.7H30.4L19.2 50.9l0.9-9.3h-0.9a6.7 6.7 0 0 1-6.7-6.7V21.1a6.7 6.7 0 0 1 6.7-6.7z"
        fill="#fff"
      />
      <path
        d="M40.6 20.7 20.9 30.4l7.4 1.7 1.6 7.4 9.7-19.7z"
        fill="#2563eb"
        transform="rotate(-6 32 30)"
      />
    </svg>
  )
}
